; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $81, $80, $35, $8d, $33, $8b, $2b, $8d, $48, $91, $2d, $9b
	.byte $48, $81, $32, $8d, $30, $8b, $27, $8d, $48, $91, $29, $9b, $48, $81, $30, $8d, $2e, $8b, $26, $8d, $48, $91, $29, $9b
	.byte $48, $81, $2e, $ab, $48, $81, $00, $ab, $48, $af, $48, $af, $48, $af, $48, $af, $48, $af, $48, $af, $48, $af, $48, $af
	.byte $42
	.word @song0ch0loop
@song0ch4:
@song0ch3:
@song0ch1:
@song0ch1loop:
@song0ref71:
	.byte $af, $af, $af, $af, $af, $af, $af, $af
	.byte $41, $08
	.word @song0ref71
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $81, $80, $35, $8d, $33, $8b, $2b, $8d, $81, $2b, $8d, $2d, $8b, $2d, $8d, $81, $32, $8d, $30, $8b, $27, $8d, $81, $27
	.byte $8d, $29, $8b, $29, $8d, $81, $30, $8d, $2e, $8b, $26, $8d, $81, $26, $8d, $29, $8b, $29, $8d, $81, $2e, $8d, $2e, $8b
	.byte $2e, $8d, $81, $00, $ab
	.byte $41, $08
	.word @song0ref71
	.byte $42
	.word @song0ch2loop
