; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_bold:=music_data_bold

music_data_bold:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_bold
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $22, $a5, $1d, $a5, $16, $a5, $00, $cd, $16, $a1, $00, $81, $16, $8d, $00, $81, $16, $8d, $00, $81, $16, $8d, $00, $81
	.byte $16, $91, $48, $1d, $a5, $00, $a5, $16, $a5, $00, $cd, $16, $a1, $00, $81, $16, $8d, $00, $81, $16, $8d, $00, $81, $16
	.byte $a5, $48, $22, $a5, $1d, $a5, $16, $a5, $00, $cd, $16, $a1, $00, $81, $16, $8d, $00, $81, $16, $8d, $00, $81, $16, $a5
	.byte $48, $19, $af, $00, $c3, $19, $a5, $1b, $f5, $1e, $a5, $48
	.byte $41, $50
	.word @song0ref6
	.byte $48
	.byte $41, $50
	.word @song0ref6
	.byte $48
	.byte $41, $50
	.word @song0ref6
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref106:
	.byte $08, $a5, $0a, $c9, $00, $81, $0a, $a1, $00, $81
@song0ref116:
	.byte $0a, $f5, $00, $a5, $08, $a5, $0a, $c9, $00, $81, $0a, $a1, $00, $81, $0a, $f5, $00, $a5, $08, $a5, $0a, $c9, $00, $81
	.byte $0a, $a1, $00, $81, $0a, $f5, $00, $a5, $0d, $cd, $00, $a5, $0d, $a5, $0b, $cd, $00, $a5, $0b, $a5, $00, $ff, $ff, $bd
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $36
	.word @song0ref106
	.byte $08, $a5, $0a, $cd, $0a, $a5
	.byte $41, $2c
	.word @song0ref116
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref190:
	.byte $0a, $cd, $00, $cd, $0a, $a1, $00, $81, $0a, $8d, $00, $81, $0a, $8d, $00, $81, $0a, $8d, $00, $81, $0a, $b5, $00, $81
	.byte $0a, $cd, $00, $cd, $0a, $a1, $00, $81, $0a, $8d, $00, $81, $0a, $8d, $00, $81, $0a, $8d, $00, $81, $0a, $b9, $0a, $cd
	.byte $00, $cd, $0a, $a1, $00, $81, $0a, $8d, $00, $81, $0a, $8d, $00, $81, $0a, $8d, $00, $81, $0a, $b9, $0d, $c9, $00, $81
	.byte $0d, $a5, $0b, $a5, $00, $91, $0b, $b9, $0b, $cd
	.byte $41, $52
	.word @song0ref190
	.byte $41, $52
	.word @song0ref190
	.byte $41, $4d
	.word @song0ref190
	.byte $ff, $9d, $42
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
@song0ref288:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $18
	.word @song0ref288
	.byte $42
	.word @song0ch3loop
