; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Swimming:

.export _music_data_swimming:=music_data_swimming

music_data_swimming:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 2, 0

.export music_data_swimming
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env3,@env4,@env0 ; 00 : Instrument 1
	.word @env2,@env3,@env4,@env0 ; 01 : Instrument 2
	.word @env5,@env3,@env4,@env0 ; 02 : Instrument 3

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $00,$ca,$7f,$00,$02
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $7f,$00,$00
@env5:
	.byte $00,$c2,$7f,$00,$02

@samples:

@tempo_env_1_mid:
	.byte $03,$06,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $81, $80, $2f, $8b, $1f, $89, $2b, $8b, $2d, $8b, $48, $81
	.byte $1f, $8b, $2f, $89, $1f, $8b, $2f, $8b, $48, $81, $1f, $8b, $26, $89, $2b, $8b, $1f
@song0ref34:
	.byte $8b, $48, $81, $2d, $8b, $1f, $89, $32, $8b, $1f
@song0ref44:
	.byte $8b, $48, $81, $2f, $8b, $1c, $89, $2b, $8b, $2d, $8b, $48, $81, $1c, $8b, $34, $89, $1c, $8b, $32, $8b, $48, $81, $1a
	.byte $8b, $2d, $89, $2b, $8b, $1a, $8b, $48, $81, $26, $8b, $1a, $89, $2b, $8b, $2d
	.byte $41, $0d
	.word @song0ref44
	.byte $2f, $89, $1c, $8b, $2f, $8b, $48, $81, $1c, $8b, $28, $89, $2b, $8b, $1c
	.byte $41, $0b
	.word @song0ref34
	.byte $2d, $8b, $1a, $89, $26, $8b, $28, $8b, $48, $81, $1a, $8b, $2b, $89, $1a, $8b, $2b, $8b, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $81, $82, $2f
@song0ref130:
	.byte $8b, $1f, $89, $2f, $8b, $1f, $8b, $81, $2b, $8b, $2d, $89, $1f, $8b, $2f, $8b, $81, $1f, $8b, $2f, $89, $1f, $8b, $26
	.byte $8b, $81, $2b, $8b, $1f, $89, $2d, $8b, $1f, $8b, $81, $32
	.byte $41, $0c
	.word @song0ref130
	.byte $1c, $8b, $34, $8b, $81, $1c, $8b, $32, $89, $1a, $8b, $2d, $8b, $81, $2b, $8b, $1a, $89, $26, $8b, $1a, $8b, $81, $2b
	.byte $8b, $1a, $89, $2f, $8b, $1c, $8b, $81, $2b, $8b, $2d, $89, $1c, $8b, $2f, $8b, $81, $1c, $8b, $2f, $89, $1c, $8b, $28
	.byte $8b, $81, $2b, $8b, $1c, $89, $2d, $8b, $1f, $8b, $81, $32, $8b, $1f, $89, $2d, $8b, $1a, $8b, $81, $26, $8b, $28, $89
	.byte $1a, $8b, $2b, $8b, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $87, $84, $13, $81, $00, $81
@song0ref255:
	.byte $13, $89, $1f, $8b, $13, $8b, $81, $00, $8b
	.byte $41, $09
	.word @song0ref255
	.byte $41, $09
	.word @song0ref255
	.byte $1f, $89, $13, $8b, $00, $81, $1f
@song0ref277:
	.byte $87, $81, $00, $83, $11, $81, $00, $81
@song0ref285:
	.byte $11, $89, $1d, $8b, $11, $8b, $81, $00, $8b
	.byte $41, $09
	.word @song0ref285
	.byte $10, $89, $1c, $8b, $10, $8b, $81, $00, $8b, $1c, $89, $10, $8b, $00, $81, $1c
	.byte $41, $11
	.word @song0ref277
	.byte $41, $09
	.word @song0ref285
	.byte $41, $09
	.word @song0ref285
	.byte $1c, $89, $10, $8b, $00, $81, $1c
	.byte $41, $11
	.word @song0ref277
	.byte $11, $89, $1d, $8b, $11, $8b, $42
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
	.byte $b7, $b7, $b7, $b7, $b7, $b7, $b7, $b7, $b7, $b7, $b7, $b7, $b7, $b7, $42
	.word @song0ch3loop
