; This file is for the FamiTone2 library and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @pal
	.word @pal
@pal:
	.word @sfx_pal_song_1
	.word @sfx_pal_song_2

@sfx_pal_song_1:
	.byte $8a,$02,$89,$3f,$01,$8a,$04,$01,$8a,$0d,$01,$8a,$02,$8a,$04,$01
	.byte $8a,$0d,$01,$8a,$02,$01,$8a,$04,$01,$8a,$0d,$8a,$02,$01,$8a,$0f
	.byte $01,$8a,$01,$01,$8a,$0a,$01,$8a,$0f,$01,$8a,$01,$01,$8a,$0a,$8a
	.byte $0f,$01,$8a,$01,$01,$8a,$0a,$01,$8a,$0f,$01,$00
@sfx_pal_song_2:
	.byte $89,$f0,$01,$8a,$0e,$89,$3f,$19,$00

.export sounds
